apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
  labels:
   kubernetes.io/metadata.name: openshift-adp
   pod-security.kubernetes.io/audit: privileged
   pod-security.kubernetes.io/enforce: privileged
   pod-security.kubernetes.io/warn: privileged
   security.openshift.io/scc.podSecurityLabelSync: 'true'