apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: app-core-dpa-kopia
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        config:
          profile: default
          region: localstorage
          s3ForcePathStyle: 'true'
          s3Url: 'http://minio-service.minio.svc.cluster.local:9000/'
        credential:
          key: cloud
          name: minio-credentials
        default: true
        objectStorage:
          bucket: backups
          prefix: velero
        provider: aws
  configuration:
    nodeAgent:
      enable: true
      uploaderType: kopia
    velero:
      defaultPlugins:
        - openshift
        - aws
        - csi
        - kubevirt
      defaultSnapshotMoveData: true
      featureFlags:
        - EnableCSI
  snapshotLocations:
    - velero:
        config:
          profile: default
          region: localstorage
        provider: aws