apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: oadp-dpa
  namespace: oadp-user1
  labels:
    app.kubernetes.io/instance: oadp-user1
spec:
  backupLocations:
    - velero:
        config:
          profile: default
          region: localstorage
          s3ForcePathStyle: 'true'
          s3Url: 'http://s3.openshift-storage.svc'
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: backups-66da4380-ff58-470d-9ecd-e79a1763dab8
          prefix: velero
        provider: aws
  configuration:
    velero:
      defaultPlugins:
        - csi
        - openshift
        - aws
        - kubevirt
      featureFlags:
        - EnableCSI