apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: 'https://github.com/mmartofel/oadp-backup'
  labels:
    app: impressive-app
    app.kubernetes.io/component: database
    app.kubernetes.io/name: store
    app.kubernetes.io/part-of: DATA_SUBSYSTEM
    app.openshift.io/runtime: postgresql
  name: postgres-db
  namespace: app-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impressive-app
  template:
    metadata:
      labels:
        app: impressive-app
    spec:
      containers:
      - name: postgres-db
        imagePullPolicy: IfNotPresent
        image: registry.redhat.io/rhel8/postgresql-12:latest
        ports:
          - containerPort: 5432
            protocol: TCP
        envFrom:
          - configMapRef:
             name: postgres-setup-configmap
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        volumeMounts:
            - name: postgres-data-volume
              mountPath: '/var/lib/pgsql/data'
      volumes:
       - name: postgres-data-volume
         persistentVolumeClaim:
          claimName: postgres-db-pvc
