apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: impressive-app
  name: postgres-db-pvc
  namespace: app-core
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi